version: '3.1'
services:
  flask:
    build: 
      context: ./flask-server
      dockerfile: Dockerfile.server
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "server:create_server()"
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./flask-server:/app
      - ./db:/app/db
      - ./utils:/app/utils
    networks:
      my-network:
        aliases:
          - flask-app

  frontend:
    build: 
      context: ./app_frontend
      dockerfile: Dockerfile.client
    volumes:
      - ./app_frontend:/app
    ports:
      - 19006:19006
    networks:
      - my-network
    depends_on:
      - flask

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - flask
      - frontend
    networks:
      - my-network

networks:
  my-network:
