version: '3'
services:
  flask_server:
    build: 
      context: .
      dockerfile: flask_server/Dockerfile.server
    volumes:
      - ./flask_server:/app
    ports:
      - 5001:5000
    restart: always
    networks:
      - mynetwork


  frontend:
    build: 
      context: ./app_frontend
      dockerfile: Dockerfile.client
    volumes:
      - ./app_frontend:/app
    ports:
      - 19006:19006
    restart: always
    networks:
      - mynetwork


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    restart: always
    depends_on:
      - frontend
      - flask_server
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
