# Use an official Node runtime as a parent image
FROM node:16

WORKDIR /app

COPY package*.json ./
COPY node_modules ./node_modules
RUN npm install -g expo-cli

COPY . .

CMD ["expo", "start", "--web"]