# Use an official Node runtime as a parent image
FROM node:16

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json first for optimized caching
COPY package*.json ./

# Copy the rest of the application
COPY . .

# Expose the port that the app runs on
EXPOSE 3000


# Define the command to run the app

CMD ["npm", "start"]
