FROM python:3.8-slim

ENV CONTAINER_HOME=/var/www

WORKDIR $CONTAINER_HOME

# Install the required packages first to leverage Docker layer caching
ADD requirements.txt $CONTAINER_HOME/
RUN apt-get update && apt-get install -y net-tools lsof
RUN pip install -r requirements.txt

# Add the rest of the files
ADD . $CONTAINER_HOME
