FROM python:3.8-slim

ENV CONTAINER_HOME=/var/www

ADD . $CONTAINER_HOME
WORKDIR $CONTAINER_HOME

RUN apt-get update && apt-get install -y net-tools lsof
RUN pip install -r $CONTAINER_HOME/requirements.txt
