# Set base image
FROM nginx:1.15

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom configuration file from the current directory
COPY default.conf /etc/nginx/conf.d/
