CREATE CONSTRAINT FOR (n:Person) REQUIRE n.Email IS UNIQUE;
CREATE CONSTRAINT FOR (n:Person) REQUIRE n.UUID IS UNIQUE;
CREATE CONSTRAINT FOR (n:Person) REQUIRE n.Username IS UNIQUE;
CREATE CONSTRAINT FOR (event:Event) REQUIRE event.UUID IS UNIQUE;
