FROM python:3.8-slim-buster
WORKDIR /app
COPY ./flask_server .
COPY ./requirements.txt .
COPY ./db ./db
COPY ./utils ./utils
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["python", "server.py"]
# CMD ["tail", "-f", "/dev/null"]
