FROM python:3.8-slim-buster
COPY ./flask_server /app/
COPY ./requirements.txt /app/
COPY ./db /app/db
COPY ./utils /app/utils
WORKDIR /app
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["python", "server.py"]
# CMD ["tail", "-f", "/dev/null"]
